import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const yandexSansText = localFont({
  src: [
    {
      path: '../public/fonts/YandexSansText-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/YandexSansText-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
  ],
  variable: '--font-yandex-sans-text',
});

const kaSansDesign = localFont({
  src: [
    {
      path: '../public/fonts/5kaSansDesign-Regular.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-5ka-sans-design',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${yandexSansText.variable} ${kaSansDesign.variable} ${yandexSansText.className} antialiased overflow-hidden`}
      >
        {/* <img src='/bg/сhristmas-tree.webp'/> */}
        <video
          // @ts-expect-error pip is not supported yet in ts
          pip='false'
          playsInline
          muted
          autoPlay
          loop
          src={'/bg/bg_video.mp4'}
          className='object-cover z-[-1] relative h-screen w-screen'
        />
        {children}
      </body>
    </html>
  );
}
